@echo off
echo Starting Honeycutt Budget Planner...
echo.
echo Starting Vite dev server...
start "Vite Dev Server" cmd /k "npm run dev:renderer"
timeout /t 5
echo Starting Electron...
npm run build:main && electron .
